version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      # - "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--serverstransport.insecureskipverify=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--accesslog.fields.names.StartUTC=drop"
      - "--accesslog.filepath=/letsencrypt/access.log"
      - "--accesslog.format=json"
      - "--accesslog.filters.statuscodes=200,300-302"
      - "--accesslog.filters.retryattempts"
      - "--accesslog.filters.minduration=10ms"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dash.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.middlewares.simpleauth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.traefik.middlewares=simpleauth@docker"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    networks:
      - internal
      - web
  myblog:
    image: case0sh/blogis:latest
    container_name: "service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myblog.rule=Host(`myblog.${DOMAIN}`)"
      - "traefik.http.routers.myblog.entrypoints=websecure"
      - 'traefik.http.routers.myblog.tls=true'
      - "traefik.http.routers.myblog.tls.certresolver=myresolver"
      - "traefik.http.middlewares.simpleauth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.myblog.middlewares=simpleauth@docker"
    networks:
      - internal
      - web

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`wh.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.middlewares.simpleauth.basicauth.users=${BASIC_AUTH}"
      - "traefik.http.routers.whoami.middlewares=simpleauth@docker"
    networks:
      - internal
      - web